version: '2.1'

services:
  ezlearn:
    image: ezlearn
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3333:3333
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 index.js