version: '3.1'

services:
  new-rest:
    image: new-rest
    build: .
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 3333:3000
    volumes: 
      - ./:/app:rw
    container_name: ezlearn_web_1
    depends_on: 
      - db
  db:
    image: postgres:11.2
    restart: always
    environment: 
      - TZ="Asia/Jakarta"
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes: 
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    container_name: ezlearn_db_1
    command: ['postgres']
    ports: 
      - 5430:5432
  # adminer:
  #   image: adminer
  #   restart: always
  #   container_name: adminer
  #   ports: 
  #     - 8080:8080